#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# Install tools for Codespaces only
if [[ "${CODESPACES:-}" == 'true' ]]; then
  # Install Solargraph Ruby Language Server
  if command -v gem &>/dev/null; then
    sudo gem install --quiet solargraph
  fi
  sudo apt update
  sudo apt install silversearcher-ag
fi

# Install Maxosx tools
if [[ $(uname) == 'Darwin' ]]; then
  arch -arm64 brew install \
    fzf \
    htop \
    the_silver_searcher \
    tmux \
    gh \
    terraform \
    terragrunt \
    jq
fi
